language: android

jdk:
    - oraclejdk8

android:
    components:
        - tools
        - tools
        - build-tools-26.0.2
        - android-26
        - platform-tools
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-google-google_play_services
    licenses:
        - 'android-sdk-license-.+'
